name: Terraform Dev Destroy with OIDC

on:
  workflow_dispatch:  # Manual trigger via GitHub UI

permissions:
  id-token: write
  contents: read

jobs:
  destroy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: "projects/769831191908/locations/global/workloadIdentityPools/github-pool/providers/github-provider"
          service_account: "github-oidc-sa@amplified-brook-468711-k5.iam.gserviceaccount.com"

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Destroy
        run: terraform destroy -auto-approve
